### ISSUE TITLE
Can we also get a way to set field settings at list level?

### ISSUE THREAD

**Issue by martindr** [OfficeDev/PnP-Provisioning-Schema#13]
In our ECM rollouts we have a need to specify various field attributes at **list** level, because these may differ from one list to another. This includes:

* DefaultValue
* AllowMultipleValues
* AnchorId
* CreateValuesInEditForm
* IsPathrendered

Of course, other settings may come up. Do you folk have some ideas on how the schema could be extended to allow for this?

**Comment by PaoloPia** [comment]
Hi, thanks for your contribution. Actually, since the 2015-08 schema, we do support default values for fields. All the other capabilities that you request for are unfortunately not directly available at CSOM level. Thus, we cannot implement them. In fact, we can only do what can be done via CSOM, which we use internally in the PnP Provisioning Engine. Please feel free to submit in User Voice your request, for further CSOM implementation. I will close this PR. Thanks again.

**Comment by martindr** [comment]
Actually we do presently have scripts that provision all those via CSOM. They are all supported.
Thanks for the note on DefaultValue.
