### ISSUE TITLE
NuGet Packages, classes & schemas

### ISSUE THREAD

**Issue by pchicot** [OfficeDev/PnP-Provisioning-Schema#68]
Hi, I'm trying to apply one of the xml samples offered here using the method ApplyProvisioningTemplate to an existing SharePoint 2013 (on-premises) site. I receive a Microsoft.SharePoint.Client.ServerException: Field or Property "SiteLogoUrl" does not exist.
After dive into the code I can see that the ComposedLook class (downloaded with the package) still has the property SiteLogo, When I review the code for the OfficeDevPnP.Core.dll I see that in there this property only appears under the WebSettings class.
It seems to be a mismatch with the classes and references when you get the NuGet package.
Any help with this?

**Comment by VesaJuvonen** [comment]
Since this is more a question, would suggest to use PnP Yammer group for initial input at http://aka.ms/OfficeDevPnPYammer - we have close to 4000 members in the group helping each other on the questions, so you'll get faster support and response.

If you are doing this in on-premises, you will need to have at least April 2015 CU installed, since SiteLogoUrl was part of that release. If you do not have that installed, you will run into issues around engine using capabilities which are not yet enabled in the server side.

Let's move the discussion to Yammer, if there's any follow ups. thx.
