### ISSUE TITLE
WebSettings NoCrawl throwing error on Office 365 Dev site

### ISSUE THREAD

**Issue by smityyy** [OfficeDev/PnP-Provisioning-Schema#70]
On applying template to sub-site I am getting the following error when I used WebSettings element. What am I missing here?

**pnp:WebSettings SiteLogo="{sitecollection}/Style Library/Test/Images/site-logo.png" />**

Method not found: 'Void Microsoft.SharePoint.Client.Web.set_NoCrawl(Boolean)'. Stack Trace: at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectWebSettings.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)

**Comment by VesaJuvonen** [comment]
SInce this is not really a schema issue, rather question around the exception, would suggest that we move the discussion to PnP Yammer group at http://aka.ms/OfficeDevPnPYammer, if there's any follow ups on this.

This exception indicates that you are using some other version of the CSOM than the one coming from Nuget package. This means that your CSOM API version for some reason is not the one which we ship monthly basis as part of the PnP Core nuget package and this older version does not have the used method for SPO.

Would simply remove the CSOM references from your project and pull down the nuget version again to make this work.
