### ISSUE TITLE
Add List Custom Actions

### ISSUE THREAD

**Issue by asumner** [OfficeDev/PnP-Provisioning-Schema#76]
Could we add List Custom Actions to the PnP Schema?
... And or is it on a roadmap for implementation?
Kind Regards
Anthony

**Comment by VesaJuvonen** [comment]
Reference discussion in the Yammer - and linking things cross. Thx for the suggestion. Was not on the roadmap, since not that common, but no reason why not to include this in the next schema version.

Cross linking to Yammer discussion - https://www.yammer.com/itpronetwork/#/Threads/show?threadId=660562857

**Comment by PaoloPia** [comment]
Added with schema 201605 and August release of the engine.
